apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs/1.include_lines: '.*c.instana.robotshop.shipping.Controller.*'
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping
          image: jithendar/shipping:image_tag
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 100Mi
            limits:
              cpu: 1
              memory: 200Mi
          env:
            - name: CART_ENDPOINT
              value: "cart:8080"
            - name: DB_HOST
              value: "mysql"

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    app: shipping
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
# ---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: cart
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: cart
#   minReplicas: 1
#   maxReplicas: 10
#   targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: shipping
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       shipping
  updatePolicy:
    updateMode: "Off"
    #updateMode: "Auto"
